#!/usr/bin/env python

## Temporary script to convert web-based locks into registry-based local locks

import sys
import os
import re
import time
import fnmatch

from argparse import ArgumentParser

parser = ArgumentParser(description = 'Convert web-based locks to registry locks')
parser.add_argument('--config', '-c', metavar = 'CONFIG', dest = 'config', required = True, help = 'Configuration JSON.')

args = parser.parse_args()
sys.argv = []

## Load the configuration
from dynamo.dataformat import Configuration, Dataset, Block, ObjectError

config = Configuration(args.config)

## Set up logging (write to stdout)
from dynamo.core.executable import authorized, make_standard_logger

LOG = make_standard_logger(config.log_level)

## Start conversion
from dynamo.policy.producers.weblock import WebReplicaLock
from dynamo.core.executable import inventory, authorizer
from dynamo.registry.registry import RegistryDatabase
from dynamo.history.history import HistoryDatabase

LOG.info('Translating web-based replica locks into DB-based locks.')

expiry = time.strftime('%Y-%m-%d', time.localtime(time.time() + 3600 * 24 * 60))
comment = 'Auto-produced by dynamo'

# The registry object
registry = RegistryDatabase()
# The history object
history = HistoryDatabase()

if not authorized:
    registry.set_read_only()
    history.set_read_only()

if authorized:
    while True:
        registry.lock_app('detox', config.applock_user)
        user, service, lock_time, note, depth = registry.get_app_lock('detox')
        if user == config.applock_user:
            break

        LOG.info('Applock is held by %s:%s. Waiting 60 seconds to retry.', user, service)
        time.sleep(60)

try:
    # we process one source at a time, because each source registers mysql locks as a different user
    for name, source_conf in config.sources.items():
        try:
            service_id = registry.db.query('SELECT `id` FROM `user_services` WHERE `name` = %s', source_conf.service)[0]
        except IndexError:
            raise RuntimeError('Unknown service %s' % source_conf.service)

        user_info = authorizer.identify_user(name = source_conf.user)
        if user_info is None:
            raise RuntimeError('Unknown user %s' % source_conf.user)

        dn = user_info[2]

        LOG.info('Translating ' + name)
  
        instance_conf = Configuration(sources = {name: source_conf.clone()}, auth = config.auth)
        weblock = WebReplicaLock(instance_conf)

        loaded_locks = set()
        for item, site in weblock.get_list(inventory):
            if site is None:
                site_name = None
            else:
                site_name = site.name

            if type(item) is Dataset:
                loaded_locks.add((item.name, site_name))
            else:
                loaded_locks.add((item.full_name(), site_name))

        num_locked = 0

        registry.db.lock_tables(write = ['detox_locks'], read = ['user_services'])

        try:
            existing_lock_ids = {}
            sql = 'SELECT `id`, `item`, `sites` FROM `detox_locks` WHERE `user` = %s AND `service_id` = %s'
            for lid, item, site in registry.db.xquery(sql, source_conf.user, service_id):
                existing_lock_ids[(item, site)] = lid
    
            existing_locks = set(existing_lock_ids.iterkeys())
    
            # lock new appearences
            for item, site in loaded_locks - existing_locks:
                sql = 'INSERT INTO `detox_locks` (`item`, `sites`, `lock_date`, `expiration_date`, `user`, `dn`, `service_id`, `comment`)'
                sql += ' VALUES (%s, %s, NOW(), %s, %s, %s, %s, \'Auto-produced by dynamo\')'
                if authorized:
                    registry.db.query(sql, item, site, expiry, source_conf.user, dn, service_id)
    
                num_locked += 1

        finally:
            registry.db.unlock_tables()

        num_unlocked = 0

        history_user_id = history.save_users([(source_conf.user, dn)], get_ids = True)[0]
        history_service_id = history.save_user_services([source_conf.service], get_ids = True)[0]

        # unlock excess
        for item, site in existing_locks - loaded_locks:
            sql = 'INSERT INTO `detox_locks` (`id`, `item`, `sites`, `groups`, `lock_date`, `unlock_date`, `expiration_date`, `user_id`, `service_id`, `comment`)'
            sql += ' SELECT `id`, `item`, `sites`, `groups`, `lock_date`, NOW(), `expiration_date`, %s, %s, `comment` FROM `dynamoregister`.`detox_locks` WHERE `id` = %s'
            if authorized:
                history.db.query(sql, history_user_id, history_service_id, existing_lock_ids[(item, site)])
                registry.db.query('DELETE FROM `detox_locks` WHERE `id` = %s', existing_lock_ids[(item, site)])

            num_unlocked += 1
    
        LOG.info('Locked: %d, Unlocked: %d', num_locked, num_unlocked)

finally:
    if authorized:
        registry.unlock_app('detox', config.applock_user)
